# Generated by Django 4.0.1 on 2022-01-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('published', models.DateField(auto_now_add=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('Fiction', 'fiction'), ('Non-Fiction', 'non-fiction'), ('Poetry', 'poetry'), ('Journal', 'journal')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
