# Generated by Django 4.0.1 on 2022-03-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_language_alter_blog_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='titles',
            field=models.IntegerField(null=True),
        ),
    ]
