# Generated by Django 4.0.1 on 2022-03-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_language_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'fiction'), ('Non-Fiction', 'non-fiction'), ('Poetry', 'poetry'), ('Journal', 'journal'), ('Biography', 'biography'), ('Textbook', 'textbook'), ('Self-Help', 'self-help'), ('Encyclopedia', 'encyclopedia'), ('Dictionary', 'dictionary'), ('Other', 'other')], max_length=64),
        ),
    ]
