# Generated by Django 4.0.1 on 2022-03-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('titles', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Audio Language',
                'verbose_name_plural': 'Audio Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AudioTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Audio Hashtag',
                'verbose_name_plural': 'Audio Hashtags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AudioPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('audio', models.FileField(upload_to='media/audioposts/audiodiles/')),
                ('genre', models.CharField(choices=[('Fiction', 'fiction'), ('Non-Fiction', 'non-fiction'), ('Poetry', 'poetry'), ('Journal', 'journal')], max_length=64)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_by', to='userapp.author')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_in', to='audiopostapp.audiolanguage')),
                ('tags', models.ManyToManyField(related_name='tags', to='audiopostapp.AudioTag')),
            ],
            options={
                'verbose_name': 'Audio Post',
                'verbose_name_plural': 'Audio Posts',
                'ordering': ['-added'],
            },
        ),
    ]
