# Generated by Django 4.0.1 on 2022-03-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiopostapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiopost',
            name='audio',
            field=models.FileField(upload_to='https://s3.amazonaws.com/audiopostapp-audio-files/'),
        ),
    ]
