# Generated by Django 4.0.1 on 2022-04-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_key',
            field=models.BooleanField(default=False),
        ),
    ]
