# Generated by Django 4.0.1 on 2022-05-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_user_has_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('user_admin', 'User Administrator'), ('maintainence', 'Maintainence Administrator'), ('moderator', 'Moderator'), ('normal_user', 'Normal User')], default='normal_user', max_length=32, null=True),
        ),
    ]
